R: "R_LIBS_USER=/hpc/users/hoffmg01/.Rlib/R_410/ /hpc/packages/minerva-centos7/R/4.1.0-cairo/lib64/R/bin/R"

scripts: "scripts/"
utils: "scripts/utils.R"

dids: ["nps"]
sids: "meta/sim_ids.json"
mids: "meta/meth_ids.csv"

sim_pars: "meta/sim_pars/"
run_pars: "meta/run_pars/"
meth_pars: "meta/meth_pars/"

raw_data: "data/raw_data/"
sim_data: "data/sim_data/"

results: "results/"
figures: "figures/"
plots: "plots/"
logs: "logs/"
   