utils:    "scripts/utils.R"

raw_data: "data/raw_data"
sim_data: "data/sim_data"

dat_ids:   ["kang", "magl"]
sim_ids:    "metadata/sim_ids.txt"
method_ids: "metadata/method_ids.csv"

data_pars: "metadata/data_pars"
sim_pars:  "metadata/sim_pars"
meth_pars: "metadata/meth_pars"
anno_tbl:  "metadata/anno_tbl.rds"

scripts: "scripts"
results: "results"
figures: "figures"

plotting: "scripts/plotting"
