utils:    "scripts/utils.R"
data_ids: ["kang"]

raw_data: "data/raw_data"
sim_data: "data/sim_data"

sim_ids:   "metadata/sim_ids.txt"
agg_ids:   "metadata/agg_ids.txt"
sim_pars:  "metadata/sim_pars"
data_pars: "metadata/data_pars"

pb_pars:    "metadata/pb_pars.csv"
mm_pars:    "metadata/mm_pars.csv"
ad_pars:    "metadata/ad_pars.csv"
mast_pars:  "metadata/mast_pars.csv"
scdd_pars:  "metadata/scdd_pars.csv"
method_ids: "metadata/method_ids.csv"

scripts: "scripts"
results: "results"
figures: "figures"